### ISSUE TITLE
win10操作系统闪退

### ISSUE THREAD

**Issue by finaldusk** [idirect3d/lakey#4]
win10操作系统打开程序后闪退，试过好几台电脑了都是这种情况，望修复

**Comment by idirect3d** [comment]
非常高兴看到您在使用Lakey，也非常感谢您能够告知我Lakey的使用问题。

限于个人水平和精力，这个软件还有非常多的不足和bug。有可能在不少环境都有无法启动的问题，特别是在部分win7及较新的操作系统。对于您反映的问题，您可以做以下尝试：

1、检查一下音频输入设备是否连接好，有的时候插一个麦克风就可以运行了。
2、删除Lakey.exe文件所在目录下的.ini文件（相当于恢复初始设置），再执行一下试试。
3、解压附件，看看您的lakey目录下有没有这几个文件，如果没有，可以将几个文件放到与Lakey.exe相同的目录试一下。

如果还不行，您可以将问题截图发给我再看一下。

VY，73

**Comment by idirect3d** [comment]
b0020版本已解决
