### ISSUE TITLE
windows 10 运行报错

### ISSUE THREAD

**Issue by glpc** [idirect3d/lakey#5]
下载后，解压直接使用报错，报错窗口信息：
           **Lakey.exe 已停止工作**
由于出现问题，程序停止正常工作。windows将关闭程序，
并会在有可用的解决方案时通知你。
                                   调试(D)         关闭程序(C)

我单击了，调试按钮。visual studio 2019进行进行查看。
显示内容：
**未加载 Lakey.pdb**
Lakey.pdb包含查找模块Lakey.exe的源文件所需的调度信息
调用堆栈，窗口
Lakey.exe!0069d335()
Lakey.exe![下面的框架可能不正解和/或后缺失，没有为Lakey。exe加载符号]

还没完，我到百度下，搜索。【对一些站点提供的文件】进行下载和安装。
也报错。

还没完，就想如果是不兼容，那自己将源码，编译一下，总能在自己的电脑上运行吧。
打开源码，进行编译。也报错。
1>CommFunc.cpp
1>C:\Users\Administrator\Downloads\Compressed\lakey-master\lakey-master\src\CommFunc.cpp(28,3): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\Users\Administrator\Downloads\Compressed\lakey-master\lakey-master\src\CommFunc.cpp(42,3): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\Users\Administrator\Downloads\Compressed\lakey-master\lakey-master\src\CommFunc.cpp(54,3): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\Users\Administrator\Downloads\Compressed\lakey-master\lakey-master\src\CommFunc.cpp(69,3): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\Users\Administrator\Downloads\Compressed\lakey-master\lakey-master\src\CommFunc.cpp(82,3): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\Users\Administrator\Downloads\Compressed\lakey-master\lakey-master\src\CommFunc.cpp(96,3): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>C:\Users\Administrator\Downloads\Compressed\lakey-master\lakey-master\src\CommFunc.cpp(109,3): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>正在生成代码...
1>LINK : fatal error LNK1104: 无法打开文件“WinIo.lib”
1>已完成生成项目“Lakey.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

WinIo.lib无法打开。

**Comment by idirect3d** [comment]
您好！

您可以先看一下windows的音频“输入”设备是否已经打开，通常插一个麦克风就好了。

**Comment by glpc** [comment]
确实。我尝试接上PC的耳机，运行就不报错了。这个什么原因？能修复这个Debug吗？

**Comment by idirect3d** [comment]
b0020版本已解决
