### ISSUE TITLE
Windows 11 运行 Koch 训练报错

### ISSUE THREAD

**Issue by MrPeterJin** [idirect3d/lakey#7]
开发者您好！

这里看到了您制作的 CW 练习器，首先十分感谢您的工作。这里在 Windows 11 使用的时候遇到了一点问题。在运行 Koch 训练法的时候，无论如何输入字符，都会弹出如下错误：

![image](https://user-images.githubusercontent.com/51412849/144843338-a56e1e79-8e1a-4e77-b86e-04a56c5339b4.png)

输入的对应界面如下：

![image](https://user-images.githubusercontent.com/51412849/144843439-e397b700-0c54-4689-bb5f-f5d1bd5a5e45.png)

这里的输入规则感觉写的也不是很清楚，是输入对应字符之后用空格隔开吗？应该有相应提示说明。

BH8CGG 敬上

**Comment by bh1rio** [comment]
遇到同样的问题

**Comment by idirect3d** [comment]
非常感谢反馈问题的朋友，由于之前没有win11，无法测试。最近新升级了win11，但按照上面朋友们的方法，未能重现报错。我重新编译了程序并且进行了更新，请有问题的朋友尝试下载新的程序，如果还报错可以尝试删除lakey.ini文件再试一下。

**Comment by bh1rio** [comment]
在我的win11上，已经没问题了
